name: Code Format
on:
  # see ready.yml
  repository_dispatch:
    types: [ready-for-release]
jobs:
  code-format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Format Code
        uses: AutoModality/action-ros-clang-format@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
